
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 87
#define YY_END_OF_BUFFER 88
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[273] =
    {   0,
        0,    0,   88,   86,   14,    5,   65,   54,   16,   64,
       53,   51,   61,   61,   61,   86,   61,    8,    8,   52,
       86,    6,   86,   84,   85,   62,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   66,   67,   14,   63,    0,   13,    0,
       80,   79,    0,    0,   59,   73,   68,   71,   69,    0,
        9,   72,    0,   11,   58,   57,   74,   11,    8,    0,
        0,   75,   70,   76,   55,    0,    0,   85,    0,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   30,   85,
       85,   85,   85,   85,   35,   85,   85,   85,   40,   85,

       85,   85,   85,   85,   85,   85,   85,   77,   81,    0,
       12,   12,   56,   11,   10,   82,   83,    0,   18,   85,
       85,   85,   85,   85,   23,   85,   85,   85,   85,   85,
       85,   33,    0,    4,   85,    1,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,    0,   12,   78,
       17,   85,   85,   21,   22,   85,   85,   24,   85,   85,
       85,   31,   85,    0,    0,   85,   38,   39,   85,   85,
       85,   85,   85,   85,   85,   85,   48,   85,    0,   85,
       20,   25,   85,   85,   85,   85,   85,    2,    0,   36,
       85,   85,   42,   85,   85,   85,   85,   85,   85,   49,

        0,   85,   85,   85,   27,   28,   32,    0,   85,   41,
       43,   44,    3,   45,   46,   85,    0,   19,   85,   29,
        0,   37,   47,    0,    0,    0,    0,   26,   34,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    7,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   60,    0,
        0,    0,    0,    0,   50,    0,    0,    0,    0,    0,
       15,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    1,    8,    9,   10,
       10,   11,   12,   10,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   10,   19,
       20,   21,   22,    1,   23,   23,   23,   24,   23,   23,
       25,   25,   25,   25,   25,   25,   25,   25,   26,   27,
       25,   28,   25,   29,   25,   25,   25,   25,   25,   25,
       10,   30,   10,   31,    1,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   25,   41,   42,   43,   44,
       45,   46,   25,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   10,   56,   10,   57,    1,    1,   58,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   59,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   60,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[61] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    3,    3,    1,    1,    1,
        1,    1,    3,    3,    2,    2,    2,    2,    2,    1,
        1,    3,    3,    3,    3,    3,    3,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[277] =
    {   0,
        0,    0,  597,  608,   59,  608,  576,   56,  608,   56,
       57,  608,   50,   55,   64,   55,   68,   75,   79,  608,
       54,  575,   77,  608,   76,  534,   93,   94,   95,  100,
      102,  104,  106,  111,  113,  115,  120,  124,  147,  149,
      153,  155,  157,   98,  608,  103,  608,   84,  608,  590,
      608,  608,  139,  589,  608,  608,  608,  608,  578,  115,
      151,  608,  576,  156,  608,  608,  608,  158,  162,    0,
      569,  608,  608,  608,  567,  164,  172,  171,  528,  176,
      178,  184,  186,  197,  199,  203,  204,  209,  208,  214,
      210,  219,  226,  215,  227,  231,  232,  233,  243,  244,

      250,  251,  255,  261,  263,  265,  272,  608,  608,  572,
      227,  266,  608,  268,    0,  608,  608,  525,  280,  282,
      288,  290,  298,  294,  302,  304,  308,  310,  312,  319,
      314,  320,  534,  326,  327,  331,  338,  342,  350,  352,
      354,  356,  358,  362,  366,  368,  364,  568,  322,  608,
      372,  373,  374,  378,  379,  383,  385,  387,  395,  404,
      408,  412,  410,  544,  517,  414,  418,  420,  422,  424,
      429,  428,  433,  437,  438,  445,  447,  449,  542,  451,
      456,  457,  461,  469,  470,  478,  480,  482,  507,  608,
      484,  486,  488,  490,  492,  494,  498,  503,  504,  509,

      524,  514,  515,  519,  525,  527,  529,  495,  535,  537,
      539,  543,  544,  545,  550,  551,  537,  561,  563,  567,
      483,  568,  569,  480,  462,  470,  442,  573,  608,  439,
      425,  407,  395,  400,  389,  390,  367,  364,  365,  344,
      318,  314,  314,  296,  608,  282,  270,  266,  260,  243,
      231,  242,  239,  235,  206,  186,  190,  157,  608,  151,
      161,  155,  138,   95,  608,   87,   93,   88,   84,   46,
      608,  608,  599,  602,  604,   65
    } ;

static yyconst flex_int16_t yy_def[277] =
    {   0,
      272,    1,  272,  272,  272,  272,  272,  273,  272,  272,
      274,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  275,  272,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  272,  272,  272,  272,  273,  272,  273,
      272,  272,  274,  274,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  276,
      272,  272,  272,  272,  272,  273,  274,  275,  272,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,

      275,  275,  275,  275,  275,  275,  275,  272,  272,  272,
      272,  272,  272,  272,  276,  272,  272,  272,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  272,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  272,  272,  272,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  272,  272,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  272,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  272,  272,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,

      272,  275,  275,  275,  275,  275,  275,  272,  275,  275,
      275,  275,  275,  275,  275,  275,  272,  275,  275,  275,
      272,  275,  275,  272,  272,  272,  272,  275,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,    0,  272,  272,  272,  272
    } ;

static yyconst flex_int16_t yy_nxt[669] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   25,   25,   25,   25,   25,   25,    4,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       25,   36,   37,   25,   38,   25,   39,   40,   41,   25,
       42,   43,   25,   25,   25,   44,   45,    4,    4,    4,
       46,   49,   46,   51,   55,   49,   57,  115,   63,   56,
       64,   64,   71,   72,   58,   52,   59,   60,   65,   61,
       61,   76,   66,   62,   77,   50,   54,   67,   68,   49,
       69,   69,   68,  271,   69,   69,   74,   75,   76,   76,

       76,   77,   77,   77,   46,   76,   46,   76,   77,   76,
       77,   76,   77,   50,   77,  270,   76,  108,   76,   77,
       76,   77,  269,   77,  268,   76,   84,   70,   77,   76,
      111,  111,   77,   85,   86,   88,   80,  267,   82,   87,
       83,  266,   81,   90,   89,   91,   94,   49,   92,   95,
       93,   98,   76,  109,   76,   77,   96,   77,   76,   97,
       76,   77,   76,   77,  112,   77,   61,   61,   54,   49,
       99,   64,   64,  114,  114,   68,  272,   69,   69,  272,
       49,  272,  100,  272,  272,  265,  272,  101,  102,  272,
      264,  272,  272,   50,  272,  107,  263,  103,  262,  106,

      104,   54,  272,  261,  272,  272,  105,  272,  272,  272,
      119,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  122,  272,  272,  272,  260,  120,  272,  121,  133,
      124,  272,  272,  259,  272,  272,  272,  272,  272,  272,
      272,  272,  111,  111,  123,  128,  125,  126,  272,  272,
      258,  272,  272,  127,  131,  272,  272,  129,  272,  272,
      272,  130,  257,  272,  135,  132,  272,  134,  272,  272,
      272,  272,  138,  272,  256,  137,  255,  272,  254,  136,
      272,  149,  149,  114,  114,  272,  142,  272,  272,  253,
      272,  252,  139,  272,  140,  272,  272,  251,  272,  272,

      144,  143,  272,  272,  146,  141,  272,  272,  145,  272,
      272,  147,  272,  272,  250,  272,  272,  272,  272,  272,
      272,  153,  272,  164,  272,  272,  151,  272,  272,  152,
      249,  272,  272,  154,  272,  272,  272,  149,  149,  272,
      155,  159,  248,  272,  161,  163,  272,  272,  247,  160,
      272,  156,  157,  246,  162,  272,  158,  272,  272,  272,
      272,  272,  272,  272,  272,  245,  272,  272,  166,  272,
      272,  272,  272,  272,  272,  167,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  168,  272,  272,  272,  171,
      272,  272,  272,  272,  244,  272,  243,  173,  170,  169,

      272,  176,  177,  272,  172,  178,  242,  174,  180,  272,
      175,  241,  272,  272,  181,  272,  272,  272,  272,  272,
      272,  240,  272,  272,  183,  272,  272,  272,  272,  272,
      272,  182,  272,  272,  272,  239,  272,  272,  272,  238,
      237,  272,  272,  272,  184,  272,  272,  185,  236,  186,
      272,  187,  272,  272,  272,  272,  272,  272,  188,  272,
      235,  272,  272,  191,  272,  272,  272,  195,  192,  272,
      197,  198,  193,  194,  272,  272,  196,  272,  272,  199,
      234,  233,  202,  272,  200,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,

      272,  232,  272,  272,  203,  205,  272,  231,  272,  272,
      204,  272,  272,  206,  272,  230,  207,  272,  209,  272,
      272,  229,  272,  272,  272,  212,  211,  272,  221,  210,
      272,  213,  272,  272,  272,  272,  217,  272,  208,  216,
      272,  215,  272,  272,  272,  272,  214,  272,  272,  272,
      272,  272,  272,  272,  201,  272,  272,  218,  272,  272,
      224,  190,  225,  226,  219,  227,  272,  220,  272,  272,
      222,  272,  272,  272,  272,  272,  272,  272,  272,  189,
      179,  272,  165,  150,  148,  118,  117,  223,  116,  113,
      110,  272,  272,   79,   73,   47,  272,  272,  228,   48,

       48,   48,   53,   53,   53,   78,   78,    3,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272
    } ;

static yyconst flex_int16_t yy_chk[669] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    8,    5,   10,   13,   11,   14,  276,   16,   13,
       16,   16,   21,   21,   14,   10,   15,   15,   17,   15,
       15,   25,   17,   15,   25,    8,   11,   17,   18,   48,
       18,   18,   19,  270,   19,   19,   23,   23,   27,   28,

       29,   27,   28,   29,   46,   30,   46,   31,   30,   32,
       31,   33,   32,   48,   33,  269,   34,   44,   35,   34,
       36,   35,  268,   36,  267,   37,   29,   18,   37,   38,
       60,   60,   38,   29,   29,   30,   27,  266,   28,   29,
       28,  264,   27,   31,   30,   32,   34,   53,   32,   35,
       33,   37,   39,   44,   40,   39,   35,   40,   41,   36,
       42,   41,   43,   42,   61,   43,   61,   61,   53,   76,
       38,   64,   64,   68,   68,   69,   78,   69,   69,   78,
       77,   80,   39,   81,   80,  263,   81,   40,   40,   82,
      262,   83,   82,   76,   83,   43,  261,   40,  260,   42,

       40,   77,   84,  258,   85,   84,   41,   85,   86,   87,
       80,   86,   87,   89,   88,   91,   89,   88,   91,   90,
       94,   83,   90,   94,   92,  257,   81,   92,   82,   93,
       85,   93,   95,  256,   93,   95,   96,   97,   98,   96,
       97,   98,  111,  111,   84,   88,   86,   87,   99,  100,
      255,   99,  100,   87,   91,  101,  102,   89,  101,  102,
      103,   90,  254,  103,   96,   92,  104,   94,  105,  104,
      106,  105,   98,  106,  253,   97,  252,  107,  251,   96,
      107,  112,  112,  114,  114,  119,  103,  120,  119,  250,
      120,  249,  100,  121,  101,  122,  121,  248,  122,  124,

      104,  103,  124,  123,  106,  102,  123,  125,  105,  126,
      125,  107,  126,  127,  247,  128,  127,  129,  128,  131,
      129,  122,  131,  132,  130,  132,  120,  130,  132,  121,
      246,  134,  135,  123,  134,  135,  136,  149,  149,  136,
      124,  128,  244,  137,  129,  131,  137,  138,  243,  128,
      138,  126,  126,  242,  130,  139,  127,  140,  139,  141,
      140,  142,  141,  143,  142,  241,  143,  144,  135,  147,
      144,  145,  147,  146,  145,  137,  146,  151,  152,  153,
      151,  152,  153,  154,  155,  138,  154,  155,  156,  141,
      157,  156,  158,  157,  240,  158,  239,  143,  140,  139,

      159,  145,  146,  159,  142,  147,  238,  143,  152,  160,
      144,  237,  160,  161,  153,  163,  161,  162,  163,  166,
      162,  236,  166,  167,  157,  168,  167,  169,  168,  170,
      169,  156,  170,  172,  171,  235,  172,  171,  173,  234,
      233,  173,  174,  175,  159,  174,  175,  160,  232,  161,
      176,  162,  177,  176,  178,  177,  180,  178,  163,  180,
      231,  181,  182,  166,  181,  182,  183,  172,  169,  183,
      174,  175,  170,  171,  184,  185,  173,  184,  185,  176,
      230,  227,  180,  186,  178,  187,  186,  188,  187,  191,
      188,  192,  191,  193,  192,  194,  193,  195,  194,  196,

      195,  226,  196,  197,  183,  185,  197,  225,  198,  199,
      184,  198,  199,  186,  200,  224,  187,  200,  191,  202,
      203,  221,  202,  203,  204,  195,  194,  204,  208,  192,
      205,  196,  206,  205,  207,  206,  201,  207,  189,  199,
      209,  198,  210,  209,  211,  210,  197,  211,  212,  213,
      214,  212,  213,  214,  179,  215,  216,  202,  215,  216,
      217,  165,  217,  217,  203,  217,  218,  204,  219,  218,
      209,  219,  220,  222,  223,  220,  222,  223,  228,  164,
      148,  228,  133,  118,  110,   79,   75,  216,   71,   63,
       59,   54,   50,   26,   22,    7,    3,    0,  219,  273,

      273,  273,  274,  274,  274,  275,  275,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "./Lex/nova_linguagem.l"
#line 2 "./Lex/nova_linguagem.l"

#define X 001 //Variavel_para_verificar_Fim_Arquivo_ EOF




#line 702 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 21 "./Lex/nova_linguagem.l"


#line 919 "lex.yy.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 273 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 608 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 23 "./Lex/nova_linguagem.l"
{yylval.label = yytext;return TK_TIPO_INT;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 24 "./Lex/nova_linguagem.l"
{yylval.label = yytext;return TK_TIPO_FLOAT;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 25 "./Lex/nova_linguagem.l"
{yylval.label = yytext;return TK_TIPO_STRING;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 26 "./Lex/nova_linguagem.l"
{yylval.label = yytext;return TK_TIPO_HEX;}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 27 "./Lex/nova_linguagem.l"
{}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 28 "./Lex/nova_linguagem.l"
{yylval.label = yytext; return	TK_IGUAL;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 29 "./Lex/nova_linguagem.l"

	YY_BREAK
case 8:
YY_RULE_SETUP
#line 30 "./Lex/nova_linguagem.l"
{yylval.traducao = yytext; return TK_DECIMAL;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 31 "./Lex/nova_linguagem.l"
{yylval.traducao = yytext; return TK_N_DECIMAL;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 32 "./Lex/nova_linguagem.l"
{yylval.traducao = yytext; return TK_HEX;; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 33 "./Lex/nova_linguagem.l"
{yylval.traducao = yytext;return TK_FLOAT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 34 "./Lex/nova_linguagem.l"
{printf("encontrei um  -- FLOAT \n"); }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 35 "./Lex/nova_linguagem.l"
{yylval.traducao = yytext; return TK_STRING;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 36 "./Lex/nova_linguagem.l"
{}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 40 "./Lex/nova_linguagem.l"

	YY_BREAK
case 16:
YY_RULE_SETUP
#line 41 "./Lex/nova_linguagem.l"
{printf("encontrei o # \n");}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 42 "./Lex/nova_linguagem.l"
{printf("encontrei o auto \n");}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 43 "./Lex/nova_linguagem.l"
{printf("encontrei o and \n"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 44 "./Lex/nova_linguagem.l"
{printf("encontrei o boolean \n");}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 45 "./Lex/nova_linguagem.l"
{printf("encontrei o break \n");}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 46 "./Lex/nova_linguagem.l"
{printf("encontrei o case \n");}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 47 "./Lex/nova_linguagem.l"
{printf("encontrei o char \n");}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 48 "./Lex/nova_linguagem.l"
{printf("encontrei o cin \n");}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 49 "./Lex/nova_linguagem.l"
{printf("encontrei o cout \n");}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 50 "./Lex/nova_linguagem.l"
{printf("encontrei o const \n");}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 51 "./Lex/nova_linguagem.l"
{printf("encontrei o continue \n");}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 52 "./Lex/nova_linguagem.l"
{printf("encontrei o define \n");}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 53 "./Lex/nova_linguagem.l"
{printf("encontrei o double \n");}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 54 "./Lex/nova_linguagem.l"
{printf("encontrei o default \n");}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 55 "./Lex/nova_linguagem.l"
{printf("encontrei o do \n");}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 56 "./Lex/nova_linguagem.l"
{printf("encontrei o else \n");}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 57 "./Lex/nova_linguagem.l"
{printf("encontrei o elseif \n");}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 58 "./Lex/nova_linguagem.l"
{printf("encontrei o for \n");}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 59 "./Lex/nova_linguagem.l"
{printf("encontrei o for each \n");}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 61 "./Lex/nova_linguagem.l"
{printf("encontrei o if \n"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 62 "./Lex/nova_linguagem.l"
{printf("enconteri o go To \n");}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 63 "./Lex/nova_linguagem.l"
{printf("encontrei o include \n");}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 64 "./Lex/nova_linguagem.l"
{printf("encontrei o long \n");}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 65 "./Lex/nova_linguagem.l"
{return TK_MAIN;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 66 "./Lex/nova_linguagem.l"
{printf("encontrei o OR\n ");}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 67 "./Lex/nova_linguagem.l"
{printf("encontrei o return \n");}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 68 "./Lex/nova_linguagem.l"
{printf("encontrei o short \n");}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 69 "./Lex/nova_linguagem.l"
{printf("encontrei o sizeof \n");}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 70 "./Lex/nova_linguagem.l"
{printf("encontrei o static \n");}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 71 "./Lex/nova_linguagem.l"
{printf("encontrei o struct \n");}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 72 "./Lex/nova_linguagem.l"
{printf("encontrei o switch \n");}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 73 "./Lex/nova_linguagem.l"
{printf("encontrei o typedef \n");}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 74 "./Lex/nova_linguagem.l"
{printf("encontrei o void \n");}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 75 "./Lex/nova_linguagem.l"
{printf("encontrei o while \n");}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 77 "./Lex/nova_linguagem.l"

	YY_BREAK
case 51:
YY_RULE_SETUP
#line 78 "./Lex/nova_linguagem.l"
{return *yytext;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 79 "./Lex/nova_linguagem.l"
{printf("encontrei o  : \n"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 80 "./Lex/nova_linguagem.l"
{printf("encontrei a aspas simples \n"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 81 "./Lex/nova_linguagem.l"
{printf("encontrei a aspas duplas \n"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 83 "./Lex/nova_linguagem.l"
{printf("encontrei o >> \n"); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 84 "./Lex/nova_linguagem.l"
{printf("encontrei o ... \n");}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 86 "./Lex/nova_linguagem.l"
{printf("encontrei o comentario de uma linha \n");}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 87 "./Lex/nova_linguagem.l"
{printf("encontrei o abre comentario varias linhas \n");}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 88 "./Lex/nova_linguagem.l"
{printf("encontrei o fecha omentario varias linhas \n");}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 92 "./Lex/nova_linguagem.l"

	YY_BREAK
case 61:
YY_RULE_SETUP
#line 93 "./Lex/nova_linguagem.l"
{return *yytext; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 94 "./Lex/nova_linguagem.l"
{printf("encontrei o ^ \n");}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 95 "./Lex/nova_linguagem.l"
{printf("encontrei o != \n");}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 96 "./Lex/nova_linguagem.l"
{printf("encontrei o & \n");}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 97 "./Lex/nova_linguagem.l"
{printf("encontrei o ! \n");}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 98 "./Lex/nova_linguagem.l"
{printf("encontrei o | \n");}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 99 "./Lex/nova_linguagem.l"
{printf("encontrei o ~ (complemento) \n");}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 100 "./Lex/nova_linguagem.l"
{printf("encontrei o mais mais \n");}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 101 "./Lex/nova_linguagem.l"
{printf("encontrei o menos menos \n");}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 102 "./Lex/nova_linguagem.l"
{printf("encontrei o == \n");}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 103 "./Lex/nova_linguagem.l"
{printf("encontrei o += \n");}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 104 "./Lex/nova_linguagem.l"
{printf("encontrei o -= \n");}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 105 "./Lex/nova_linguagem.l"
{printf("encontrei o *= \n");}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 106 "./Lex/nova_linguagem.l"
{printf("encontrei o /= \n");}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 107 "./Lex/nova_linguagem.l"
{printf("encontrei o <= \n");}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 108 "./Lex/nova_linguagem.l"
{printf("encontrei o >= \n");}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 109 "./Lex/nova_linguagem.l"
{printf("encontrei o |= \n");}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 110 "./Lex/nova_linguagem.l"
{printf("encontrei o ^= \n");}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 111 "./Lex/nova_linguagem.l"
{printf("encontrei o &= \n");}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 112 "./Lex/nova_linguagem.l"
{printf("encontrei o && \n");}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 113 "./Lex/nova_linguagem.l"
{printf("encontrei o || \n");}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 114 "./Lex/nova_linguagem.l"
{printf("encontrei o <<= \n");}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 115 "./Lex/nova_linguagem.l"
{printf("encontrei o >>= \n");}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 116 "./Lex/nova_linguagem.l"
{printf("encontrei o ? \n");}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 118 "./Lex/nova_linguagem.l"
{ yylval.label = yytext; return TK_ID; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 119 "./Lex/nova_linguagem.l"
{printf("ponto \n"); *yytext; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 120 "./Lex/nova_linguagem.l"
ECHO;
	YY_BREAK
#line 1413 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 273 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 273 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 272);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 119 "./Lex/nova_linguagem.l"



